### ISSUE TITLE
MeasureString won't return the width

### ISSUE THREAD

**Issue by guipaz** [EnoughTea/MonoBMFont#1]
I debugged a little bit and noticed that when there's no \n, the Vector2 returned by MeasureString won't ever have a width defined. I didn't test it exhaustively yet so I didn't create a PR, but I assume this would fix it:

**ProcessChars:141**
`return new Vector2(Math.Max(maxLineWidth, currentX), currentY);`

Hope it helps.

**Comment by EnoughTea** [comment]
Whoa, somehow I never got notification for this issue and almost missed it. Added your fix, thanks for the help, @guipaz!
